version: "3.7"

services:
  database:
    container_name: db-esponsor
    image: postgres
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=esponsordb  
    ports:
      - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
  

  backend:
    depends_on: 
      - database
    links: 
      - database
    volumes:
      - ./backend:/app
    build: ./backend
    container_name: esponsor-backend
    image: esponsor/esponsor-backend
    ports:
      - "8000:8000"
      - "80:80"
    entrypoint: sh -c "php /var/www/html/artisan migrate && apache2-foreground"

   client:
    volumes:
      - ./client:/app
    build: ./client
    links:
      - backend
    container_name: esponsor-client
    image: esponsor/esponsor-client
    ports:
      - "3000:3000"
volumes:
  db_data:

# networks:
#   backend:
#   database: